# Generated by Django 5.2 on 2025-04-08 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deep', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaivariety',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='chaivariety',
            name='image',
            field=models.ImageField(upload_to='deep/'),
        ),
    ]
